version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: monorepo_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: myapp
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:latest
    container_name: monorepo_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: monorepo_kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    command:
      - sh
      - -c
      - |
        cub kafka-ready -b localhost:9092 1 20 || exit 1
        kafka-topics --bootstrap-server localhost:9092 --create --topic my-topic --partitions 1 --replication-factor 1 || true
        /etc/confluent/docker/run
volumes:
  pgdata:
